In [3]:
import numpy as np 


In [18]:
import numpy as np 

# NUMPY INDEXING AND SLICING OF VECTORS

arr = np.arange(11,21)

print(arr)
 
#print(arr[6])

print(arr[3::2])

[11 12 13 14 15 16 17 18 19 20]
[14 16 18 20]


In [19]:
# NUMPY INDEXING AND SLICING OF MATRIX

arr = np.arange(1,31).reshape(6,5)

print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [22]:
arr[4]

array([21, 22, 23, 24, 25])