### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# code
import numpy as np
a = np.random.randint(1,100,15)
print(a , "\n")

print(np.sort(a))

[19 54 80 73 38  8 61 12 74 25  4 73 45 15 89] 

[ 4  8 12 15 19 25 38 45 54 61 73 73 74 80 89]


In [14]:
b = np.random.randint(1,100,24).reshape(6,4)

print(b , "\n")
# print(np.sort(b , "\n"))

print(np.sort(b, axis=1 ))

[[43 67 94 21]
 [39 81 59 13]
 [96 34 78 60]
 [52 75 91 70]
 [12 92 76 13]
 [23 85  6 83]] 

[[21 43 67 94]
 [13 39 59 81]
 [34 60 78 96]
 [52 70 75 91]
 [12 13 76 92]
 [ 6 23 83 85]]


In [ ]:
np.sort(a)[::-1]

array([94, 92, 78, 68, 53, 50, 38, 37, 30, 28, 21, 11,  9,  5,  2])

In [15]:
np.sort(b,axis=0)

array([[12, 34,  6, 13],
       [23, 67, 59, 13],
       [39, 75, 76, 21],
       [43, 81, 78, 60],
       [52, 85, 91, 70],
       [96, 92, 94, 83]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [19]:
# code
# np.append(a,200)

# np.append(a,200)

a

np.append(a,200)

array([ 19,  54,  80,  73,  38,   8,  61,  12,  74,  25,   4,  73,  45,
        15,  89, 200])

In [29]:
b

np.append(b , np.ones((b.shape[0],1)),axis=1)

array([[43., 67., 94., 21.,  1.],
       [39., 81., 59., 13.,  1.],
       [96., 34., 78., 60.,  1.],
       [52., 75., 91., 70.,  1.],
       [12., 92., 76., 13.,  1.],
       [23., 85.,  6., 83.,  1.]])

In [30]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)



array([[43.        , 67.        , 94.        , 21.        ,  0.44042645],
       [39.        , 81.        , 59.        , 13.        ,  0.17094288],
       [96.        , 34.        , 78.        , 60.        ,  0.38965853],
       [52.        , 75.        , 91.        , 70.        ,  0.35656882],
       [12.        , 92.        , 76.        , 13.        ,  0.53618143],
       [23.        , 85.        ,  6.        , 83.        ,  0.43632011]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [27]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [28]:
# np.concatenate((c,d),axis=0)

np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
# np.concatenate((c,d),axis=1)



array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [32]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [33]:
# np.unique(e)

np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [34]:
# code
a.shape

(15,)

In [43]:
# np.expand_dims(a,axis=0).shape

np.expand_dims(a,axis=0).shape



1

In [44]:
# np.expand_dims(a,axis=1)
np.expand_dims(a,axis=0)


1

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [45]:
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [46]:
# find all indices with value greater than 50
# np.where(a>50)

np.where(a>50)
 

(array([ 1,  2,  3,  6,  8, 11, 14]),)

In [47]:
# replace all values > 50 with 0
# np.where(a>50,0,a)

np.where(a>50,0,a)

array([19,  0,  0,  0, 38,  8,  0, 12,  0, 25,  4,  0, 45, 15,  0],
      dtype=int32)

In [48]:
# np.where(a%2 == 0,0,a)

np.where(a%2 == 0 , 0 ,a)


array([19,  0,  0, 73,  0,  0, 61,  0,  0, 25,  0, 73, 45, 15, 89],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [54]:
# code
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [56]:
# np.argmax(a)

print(np.argmax(a))

print(a[14])

14
89


In [62]:
b

array([[43, 67, 94, 21],
       [39, 81, 59, 13],
       [96, 34, 78, 60],
       [52, 75, 91, 70],
       [12, 92, 76, 13],
       [23, 85,  6, 83]], dtype=int32)

In [63]:
# np.argmax(b,axis=0)


np.argmax(b,axis=0)


array([2, 4, 0, 5])

In [64]:
np.argmax(b,axis=1)

array([2, 1, 0, 2, 1, 1])

In [65]:
# np.argmin
# np.argmin(a)

np.argmin(a)

np.int64(10)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [67]:
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [68]:
# np.cumsum(a)

np.cumsum(a)

array([ 19,  73, 153, 226, 264, 272, 333, 345, 419, 444, 448, 521, 566,
       581, 670])

In [69]:
b

array([[43, 67, 94, 21],
       [39, 81, 59, 13],
       [96, 34, 78, 60],
       [52, 75, 91, 70],
       [12, 92, 76, 13],
       [23, 85,  6, 83]], dtype=int32)

In [72]:
# np.cumsum(b,axis=1)

np.cumsum(b,axis=)

array([[ 43, 110, 204, 225],
       [ 39, 120, 179, 192],
       [ 96, 130, 208, 268],
       [ 52, 127, 218, 288],
       [ 12, 104, 180, 193],
       [ 23, 108, 114, 197]])

In [73]:
np.cumsum(b)

array([  43,  110,  204,  225,  264,  345,  404,  417,  513,  547,  625,
        685,  737,  812,  903,  973,  985, 1077, 1153, 1166, 1189, 1274,
       1280, 1363])

In [74]:
# np.cumprod
# np.cumprod(a)

np.cumprod(a
          )

array([                  19,                 1026,                82080,
                    5991840,            227689920,           1821519360,
               111112680960,        1333352171520,       98668060692480,
           2466701517312000,     9866806069248000,   720276843055104000,
       -4481030209939423232,  6571523145746857984, -5430250387235291136])

In [75]:
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [77]:
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [80]:
# np.percentile(a,50)

np.percentile(a,100)

np.percentile(a,0)

np.percentile(a,50)

np.float64(45.0)

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [81]:
# np.histogram(a,bins=[0,50,100])

np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [85]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])


# np.corrcoef(salary,experience)
np.corrcoef(salary,experience)


array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [91]:
# code
a


array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [93]:
items = [10,20,30,40,50,60,70,80,90,100]

# a[np.isin(a,items)]

# a[np.isin(a,items)]

np.isin(a,items)

15

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [94]:
# code
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [96]:
# np.flip(a)

x= np.array([1,2,3,4,5,6,7,8,9])

np.flip(x)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [97]:
b

array([[43, 67, 94, 21],
       [39, 81, 59, 13],
       [96, 34, 78, 60],
       [52, 75, 91, 70],
       [12, 92, 76, 13],
       [23, 85,  6, 83]], dtype=int32)

In [99]:
# np.flip(b,axis=1)

np.flip(b,axis=0)

array([[23, 85,  6, 83],
       [12, 92, 76, 13],
       [52, 75, 91, 70],
       [96, 34, 78, 60],
       [39, 81, 59, 13],
       [43, 67, 94, 21]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [100]:
# code
a

array([19, 54, 80, 73, 38,  8, 61, 12, 74, 25,  4, 73, 45, 15, 89],
      dtype=int32)

In [105]:
# np.put(a,[0,1],[110,530])

np.put(a,[0,1],[111,112])

a


array([111, 112,  80,  73,  38,   8,  61,  12,  74,  25,   4,  73,  45,
        15,  89], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [107]:
# code
a = np.array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [111]:
# np.delete(a,[0,2,4])

np.delete(a,[0,1,3,4])

a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [117]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])


# np.union1d(m,n)

np.union1d(m,n)


array([1, 2, 3, 4, 5, 6, 7])

In [118]:
# np.intersect1d(m,n)

np.intersect1d(m,n)

array([3, 4, 5])

In [119]:
# np.setdiff1d(n,m)

np.setdiff1d(n,m)

array([6, 7])

In [122]:
# np.setxor1d(m,n)

np.setxor1d(m,n)

array([1, 2, 6, 7])

In [125]:
# m[np.in1d(m,1)]

m[np.in1d(m,1)]

C:\Users\shakti\AppData\Local\Temp\ipykernel_2884\3542318351.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [126]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [127]:
# np.clip(a,a_min=25,a_max=75)

np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals