In [6]:
#  ARRAY OPERATIONS 

import numpy as np



arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([6,7,8,9,1])

add = arr_1+arr_2
minus = arr_1-arr_2
multiply = arr_1*arr_2
mod = arr_1%arr_2
divide = arr_1/arr_2

print(add,minus,multiply,mod, divide,  sep=" " )



[ 7  9 11 13  6] [-5 -5 -5 -5  4] [ 6 14 24 36  5] [1 2 3 4 0] [0.16666667 0.28571429 0.375      0.44444444 5.        ]


In [14]:
# BROADCASTING

l = [10,20,30,40,50]

arr = np.array(l)

arr+10

# for i in l :
#     print(i+10)

# print(i)


array([20, 30, 40, 50, 60])

In [24]:
# arr_2 = np.arange(1,26).reshape(5,5)

# print(arr_2+10)

arr_2 = np.arange(1,31).reshape(6,5)

print(arr_2+100)

[[101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]
 [126 127 128 129 130]]


In [40]:
# DEEP AND SHALLOW COPY 


# Shallow copy 
a = np.arange(1,21)

print(a)

slice = a[:5]
slice = slice *10
print(slice)

print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[10 20 30 40 50]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [41]:
# DEEP COPY

b = a

b[0] = 100

print(a)

[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [78]:
#  MATRIX OPERATIONS

a = np.array([[1,2], [3,4]])
b = np.array([[5,6],[7,8]])

print(a)

print(b)



print(np.dot(a,b))



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [77]:
# TRANSPOSE 

print(a.T)


[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [62]:
# ADVANCE ARRAY MANIPULATION

# STACKING ARRAY

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.vstack((a,b)))

print(np.hstack((a,b)))

print(np.column_stack((a,b)))




[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [76]:
#  SPLITING ARRAY 

c = np.arange(16).reshape(4,4)


print(np.hsplit(c,4))

print(np.vsplit(c,4))



[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
