In [ ]:
import numpy as np


In [13]:

# Basic array creation 

import numpy as np

a = np.array([1,2,3,4])

print(arr)


[1 2 3 4]


In [12]:
a = np.array([1,2,3,4.5])

print(a)

np.array(a)

[1.  2.  3.  4.5]


array([1. , 2. , 3. , 4.5])

In [15]:
# array generation function

arr = np.arange(1,10)

print(arr)



[1 2 3 4 5 6 7 8 9]


In [25]:
#array zeros
arr_1 = np.zeros((4,8))

print(arr_1)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
# array ones
arr = np.ones((6,3))

print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
# array linspace

arr = np.linspace(0,5,1)

print(arr)


[0.]


In [49]:
# RANDOM GENERATION FUNCTION

np.random.rand(10)

np.random.randn(10)

np.random.randint(10,20,10) 

array([19, 14, 18, 11, 18, 13, 11, 16, 10, 11], dtype=int32)

In [72]:
# Array Attributes

arr = np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[1,2,3,4]])

print(arr.ndim)

arr.shape

arr.dtype

arr.size



3


np.int64(8)

In [97]:

# print(arr.min())

# print(arr.max())

# print(arr.sum())

# print(np.sum(arr,axis=1))

# print(np.mean(arr))

# print(arr.std)

print(np.argmax(arr))

print(np.argmin(arr))




7
0


In [107]:
# RESHAPING AND RESIZING

arr = np.arange(1,31).reshape(6,5)

print(arr)

arr_2 = np.arange(1,31).resize(6,5)

print(arr_2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
None
